export default {
  items: [
    {
      id: "navigation",
      title: "Navigation",
      type: "group",
      icon: "icon-navigation",
      children: [
        {
          id: "dashboard",
          title: "Dashboard",
          type: "item",
          url: "/dashboard/default",
          icon: "feather icon-home",
        },
      ],
    },
    {
      id: "Management",
      title: "Management",
      type: "group",
      icon: "icon-navigation",
      children: [
        {
          id: "users",
          title: "Users",
          type: "item",
          url: "/views/users",
          classes: "nav-item",
          icon: "feather icon-user",
        },
        {
          id: "category",
          title: "Categories",
          type: "item",
          url: "/views/category",
          classes: "nav-item",
          icon: "feather icon-list",
        },
        {
          id: "color",
          title: "Colors",
          type: "item",
          url: "/views/colors",
          classes: "nav-item",
          icon: "feather icon-circle",
        },
        {
          id: "orders",
          title: "Orders",
          type: "item",
          url: "/views/orders",
          classes: "nav-item",
          icon: "feather icon-activity",
        },
        {
          id: "product",
          title: "Products",
          type: "item",
          url: "/views/products",
          classes: "nav-item",
          icon: "feather icon-box",
        },
        {
          id: "coupon",
          title: "Discount",
          type: "item",
          url: "/views/coupons",
          classes: "nav-item",
          icon: "feather icon-tag",
        },
        {
          id: "noti",
          title: "Notifications",
          type: "item",
          url: "/views/notifications",
          classes: "nav-item",
          icon: "feather icon-bell",
        },
      ],
    },
  ],
};
